version: "3.8"

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"

  strapi:
    build:
      context: ./strapi
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/app
    environment:
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
