version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
#    depends_on:
#      - postgres


  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"