version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: /srv/app/database/data.db
    ports:
      - "1337:1338"
    volumes:
      - ./strapi/data:/srv/app/database
