version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AWS_BUCKET_NAME={AWS_BUCKET_NAME}
      - AWS_PUBLIC_url={AWS_PUBLIC_url}
      - AWS_REGION={AWS_REGION}
      - AWS_ACCESS_KEY_ID={AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY={AWS_SECRET_ACCESS_KEY}

    entrypoint: sh -c "PORT=3002 npm run start"
