version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  strapi:
    build: .
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - ./strapi:/usr/src/app/strapi
    environment:
      NODE_ENV: development
