version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  strapi:
    build: .
    container_name: strapi
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/data.db
      NODE_ENV: development
