version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  strapi:
    build:
      context: ./strapi
    ports:
      - "1337:1337"
    entrypoint: sh -c "npm install && npm run start"
